name: Android CI

env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  RELEASE_SIGN_KEY_ALIAS: ${{ secrets.RELEASE_SIGN_KEY_ALIAS }}
  RELEASE_SIGN_KEY_PASSWORD: ${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Retrieve Version
        run: |
          echo "version_name=$(${{github.workspace}}/gradlew -q printVersionName)" >> $GITHUB_ENV

      - name: Check tag
        uses: actions/checkout@v2
      - name: Check for Tag
        run: |
          TAG="0.1"
          if [ $(git tag -l "v${version_name}") ]; then
            echo "Tag v${version_name} already exist"
            exit 1
          fi

      - uses: mukunku/tag-exists-action@v1.4.0
        id: checkTag
        with:
          tag: v${{ env.version_name }}

      - name: Checkout keystore repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.KEYSTORE_GIT_REPOSITORY }}
          token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
          path: app/keystore

      - name: Build release artifacts
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease --stacktrace
          ./gradlew bundleRelease

      - name: Rename release file
        run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/NightwavePlaza-$version_name.apk

      - uses: actions/upload-artifact@v2
        with:
          name: Upload artifact
          path: app/build/outputs/apk/release/NightwavePlaza-${{ env.version_name }}.apk

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.version_name }}
          name: Release ${{ env.version_name }}
          files: app/build/outputs/apk/release/NightwavePlaza-${{ env.version_name }}.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
